### ISSUE TITLE
Error: Call to undefined function trigger_event()

### ISSUE THREAD

**Issue by evilsquid55555** [omerida/dokuwiki-randomtables#10]
Howdy,

I love this thing... but it suddenly stopped working.

At the moment, whenever I save a page containing a `<RANDOMTABLE>` tag, I am getting  this error:
```
Error: Call to undefined function trigger_event()
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the randomtables plugin.
More info has been written to the DokuWiki error log.

```
If I go back in my browser and save the page again (without making any changes), I do not get the error mentioned above.

When I look at the dokuwiki logs I see these two entries:

```
E_WARNING: Undefined array key "do"
/...MyWebServer.../lib/plugins/randomtables/syntax/source.php(57)
#0 /...MyWebServer.../lib/plugins/randomtables/syntax/source.php(57): dokuwiki\ErrorHandler::errorHandler()
#1 /...MyWebServer.../inc/parser/handler.php(298): syntax_plugin_randomtables_source->handle()
#2 /...MyWebServer.../inc/Parsing/Lexer/Lexer.php(269): Doku_Handler->plugin()
#3 /...MyWebServer.../inc/Parsing/Lexer/Lexer.php(185): dokuwiki\Parsing\Lexer\Lexer->invokeHandler()
#4 /...MyWebServer.../inc/Parsing/Lexer/Lexer.php(146): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens()
#5 /...MyWebServer.../inc/Parsing/Parser.php(113): dokuwiki\Parsing\Lexer\Lexer->parse()
#6 /...MyWebServer.../inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse()
#7 /...MyWebServer.../inc/parserutils.php(198): p_get_instructions()
#8 /...MyWebServer.../inc/parserutils.php(520): p_cached_instructions()
#9 /...MyWebServer.../inc/parserutils.php(299): p_render_metadata()
#10 /...MyWebServer.../inc/common.php(265): p_get_metadata()
#11 /...MyWebServer.../doku.php(101): pageinfo()
#12 {main}
```

```
Error: Call to undefined function trigger_event()
/...MyWebServer.../lib/plugins/randomtables/syntax/source.php(62)
#0 /...MyWebServer.../inc/parser/handler.php(298): syntax_plugin_randomtables_source->handle()
#1 /...MyWebServer.../inc/Parsing/Lexer/Lexer.php(269): Doku_Handler->plugin()
#2 /...MyWebServer.../inc/Parsing/Lexer/Lexer.php(185): dokuwiki\Parsing\Lexer\Lexer->invokeHandler()
#3 /...MyWebServer.../inc/Parsing/Lexer/Lexer.php(146): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens()
#4 /...MyWebServer.../inc/Parsing/Parser.php(113): dokuwiki\Parsing\Lexer\Lexer->parse()
#5 /...MyWebServer.../inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse()
#6 /...MyWebServer.../inc/parserutils.php(198): p_get_instructions()
#7 /...MyWebServer.../inc/parserutils.php(520): p_cached_instructions()
#8 /...MyWebServer.../inc/parserutils.php(299): p_render_metadata()
#9 /...MyWebServer.../inc/common.php(265): p_get_metadata()
#10 /...MyWebServer.../doku.php(101): pageinfo()
#11 {main}
```

Any attempt to actually use these newly created randomtables simply does nothing.

What's odd to me is that pages containing or referencing randomtables I made weeks ago are all working fine.

I think I broke something, but I have no idea what it is.

Help!!!  We have a game this Sunday!  hehe.

In an effort to fix things myself, I upgraded all of my plugins and then upgraded my Dokuwiki as well.
DokuWiki version: Release 2025-05-14a "Librarian"
PHP version 8.3.21

Is there a limit to the size of the database?  Is there a way to check the integrity of the database?

**Comment by omerida** [comment]
I just pushed a fix to use the new event system. Please update the plugin in the admin and let me know if it works for you. I've got it running on the latest version of dokuwiki.

**Comment by evilsquid55555** [comment]
After the update, I was still getting the error listed above when I would open a page containing a **randomtable** tag.

Since I had been attempting a whole bunch of things on my own, I decided it would be best to reinstall the randomtables plugin from scratch, so I deleted the directories related to it from the **/lib/plugins** and **/lib/tpl** directories and then reinstalled it from within **Extension Manager**.

All of the pages with randomtable data now open, but none are rendering.
The page containing the d6 table displays like this:
```
<RANDOMTABLE Rd6>
1
2
3
4
5
6
</RANDOMTABLE>
```

I figured maybe somehow I had set the plugin to disabled, so I looked in **Installed Plugins** to reenable it, but it isn't there.  It only shows up in the **Installed Templates** area (which was true yesterday as well), but there is no "enable/disable" option there.

I checked in **Configuration Manager** to see if I needed to change some settings for either RandomTables or SQLite, but neither seem to have controls there, so I don't think that is it.


Thank you, thank you, thank you for looking at all of this...  I know we all have real lives, but I also know our real lives are just there to fund our fake ones.

**Comment by evilsquid55555** [comment]
This "page loading without rendering the randomtable data" thing happened during one of my many tests yesterday, so I experimented a bit by copying directories between the the **/lib/plugins/** and **/lib/tpl/** directories.  At some point I made it happy and things started rendering again.

For your information, after deleting randomtables related directories from under **/lib/plugins/** and **/lib/tpl/** and then reinstalling it here is the current state:

Under **/lib/plugins/** there are no new directories and no directories relating to randomtables that I can see.

Under **/lib/tpl/** there is a new directory called **dokuwiki-randomtables-latest**.

If I copy that **dokuwiki-randomtables-latest** to the plugins directory and then rename it to "randomtables", and then edit a page containing randomtables data, the page renders but doesn't work.  I don't know enough about the plugin language, but it looks like part of the code that should be under the plugins directory isn't making it there.

**Comment by evilsquid55555** [comment]
I also don't know enough about SQLite, so I haven't been able to figure out how to check the database integrity or even how to restart the randomtables database from scratch.  I found the database files under /data/meta/ but I really don't know enough to be touching those.  If this were SQL on a normal SQL server, I might have some hope, but my grasp of web services and the interconnectivity of all these elements is very lacking.

**Comment by evilsquid55555** [comment]
No longer receiving an error, so the issue must be resolved.
